supporting async now
DTONeill/EventbriteApiV3 pull request #2
Opened 2020-10-08 19:24 UTC by egbertn

I added 2 methods to support async fetching

2020-11-01 16:16 UTC, DTONeill commented on EventbriteApiV3/.nuspec
> +    <releaseNotes>Initial 1.0.1 release</releaseNotes>
It's not the initial release anymore, you could remove "Initial"

2020-11-01 16:47 UTC, DTONeill requested changes

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/Attendees/AttendeeSearchEventbriteRequest.cs
> +        }
Convention: Newline between methods

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/EventbriteContext.cs
> +        }
new line here too.

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/EventbriteContext.cs
> +		public Task< AttendeeSearchApiResponse> GetAttendeesAsync(double eventId, BaseSearchCriterias searchCriterias)
remove tab before "public"

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/EventbriteRequestBase.cs
> +        protected async Task<string> GetJsonResponseAsync()
new line

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/EventbriteRequestBase.cs
> +        }
new line

2020-11-01 16:47 UTC, DTONeill commented on EventbriteApiV3/Events/EventsOrganizationRequest.cs
> +			var result = JsonSerializer.Deserialize< EventsSearchApiResponse>(new JsonTextReader( response ));
you could return result directly.

2020-11-01 16:51 UTC, DTONeill commented
Hi, i'm pretty happy to have a contributor for the project, are you an active user of the project?

2020-11-01 19:16 UTC, egbertn commented
Hi Sure, I am.


------ Origineel bericht ------
Van: "DTONeill" <notifications@github.com>
Aan: "DTONeill/EventbriteApiV3" <EventbriteApiV3@noreply.github.com>
CC: "Egbert Nierop" <egbert_nierop@outlook.com>; "Author" 
<author@noreply.github.com>
Verzonden: 1-11-2020 17:51:26
Onderwerp: Re: [DTONeill/EventbriteApiV3] supporting async now (#2)

>
>Hi, i'm pretty happy to have a contributor for the project, are you an 
>active user of the project?
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly, view it on GitHub 
><https://github.com/DTONeill/EventbriteApiV3/pull/2#issuecomment-720117629>, 
>or unsubscribe 
><https://github.com/notifications/unsubscribe-auth/AA2PPB5QWQO5VXDM4WSTME3SNWGY5ANCNFSM4SJFEFRA>.
>

2020-11-02 12:48 UTC, egbertn commented
I think I solved the issues. Let me know if all ok.

2020-11-03 01:10 UTC, DTONeill approved these changes

2020-11-03 01:11 UTC, merged