Organization
DTONeill/EventbriteApiV3 pull request #3
Opened 2020-10-30 13:27 UTC by egbertn

2020-11-03 01:27 UTC, DTONeill requested changes

2020-11-03 01:27 UTC, DTONeill commented on EventbriteApiV3/Attendees/AttendeeSearchEventbriteRequest.cs
> +        }
Put a new line between methods please.

2020-11-03 01:27 UTC, DTONeill commented on EventbriteApiV3/EventbriteContext.cs
> +        }
New line here.

2020-11-03 01:27 UTC, DTONeill commented on EventbriteApiV3/EventbriteContext.cs
> +		public Task< AttendeeSearchApiResponse> GetAttendeesAsync(double eventId, BaseSearchCriterias searchCriterias)
Remove the tab before "public"

2020-11-03 01:27 UTC, DTONeill commented on EventbriteApiV3/Events/EventSearchEventbriteRequest.cs
> +        }
new line here

2020-11-03 01:27 UTC, DTONeill commented on EventbriteApiV3/EventbriteRequestBase.cs
> +        }
new line here

2020-11-05 00:50 UTC, DTONeill requested changes
Since the conflict resolution I don't see anymore EventsOrganizationRequest or the method getEventsByOrganisation.
Look at the "files changed tab"

2020-11-05 10:00 UTC, egbertn commented
> 
> 
> Since the conflict resolution I don't see anymore EventsOrganizationRequest or the method getEventsByOrganisation.
> Look at the "files changed tab"

Cannot reproduce :( 
Done everything, git merge upstream etc. Is it an idea that you close the PR's, and I recreate one new PR?

2020-11-06 00:57 UTC, DTONeill commented
Yes i think it will be better if you create a new branch, copy paste the code and create a new pull-request.

2020-11-13 19:27 UTC, closed without merging